package com.blueapps.egyptianwriter.bliss

/**
 * A single, fully-resolved component within a [ComposedBlissWord].
 *
 * ## Patch 6 — Motivation
 * Before Patch 6, [BlissSemanticComposer] collapsed a multi-symbol
 * composition into a single [BlissSymbol] with a flat [BlissSymbol.componentIds]
 * list.  That design discarded per-component linguistic information:
 * which indicators belong to which symbol, whether a modifier is a
 * Bliss overlay or a separate linear token, and what the resolved
 * lemma of each part is.
 *
 * [ResolvedBlissComponent] preserves that information explicitly so
 * that the render layer can apply SVG overlays correctly and so that
 * future NLP stages can re-lemmatise each component independently.
 *
 * ## Bliss linguistic background
 * According to BCI Bliss rules, indicators (tense, number, evaluation)
 * are non-spacing characters that visually sit *above* the base symbol
 * (combining / overlay behaviour).  Modifiers are separate linear symbols
 * that widen the meaning of the base.  This class distinguishes both
 * via [indicators] (overlay) and [modifiers] (linear).
 *
 * @param symbol      The base [BlissSymbol] for this component.  Always non-null;
 *                    if lookup failed, use [BlissSymbol.MatchType.UNKNOWN].
 * @param lemma       The lemma that was used to resolve [symbol].  May differ
 *                    from the surface token when the composer applied
 *                    per-component re-lemmatisation.
 * @param pos         Part-of-speech tag (Morfologik tag string, e.g. "NN", "VBD").
 *                    Empty string if POS tagging was not performed.
 * @param indicators  List of Bliss indicator names to render as overlays above
 *                    [symbol] (e.g. "past", "plural", "future", "evaluation").
 *                    Must correspond to valid BCI indicator IDs recognised by
 *                    [BlissRenderer].  Empty list = no overlay.
 * @param modifiers   List of [BlissSymbol] instances that modify this component
 *                    linearly (placed adjacent, not overlaid).  Typically empty;
 *                    used for intensifiers and description qualifiers.
 * @param renderAttachments  Low-level render instructions that supplement
 *                    [indicators] with explicit pixel/vector offset hints.
 *                    Generated by [BlissRenderer] from indicator names;
 *                    may be empty when the renderer uses default positioning.
 */
data class ResolvedBlissComponent(
    val symbol:             BlissSymbol,
    val lemma:              String             = symbol.lemma,
    val pos:                String             = "",
    val indicators:         List<String>       = emptyList(),
    val modifiers:          List<BlissSymbol>  = emptyList(),
    val renderAttachments:  List<BlissRenderAttachment> = emptyList()
) {
    /** True when at least one overlay indicator is attached. */
    val hasOverlay: Boolean get() = indicators.isNotEmpty() || renderAttachments.any { it.isOverlay }

    /** True when this component resolved to a real BCI symbol (not UNKNOWN). */
    val isResolved: Boolean get() = !symbol.isUnknown
}
